CREATE TABLE item
(
    id UUID PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    DESCRIPTION TEXT,
    QUANTITY INT NOT NULL DEFAULT 0,
    DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    VERSION INT NOT NULL
);