ALTER TABLE item
    ADD COLUMN available BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE item
    ADD COLUMN price DOUBLE PRECISION NOT NULL DEFAULT 1000.00;

ALTER TABLE item
    ADD COLUMN specification VARCHAR;